In [ ]:
# Chargement package
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
import matplotlib.pyplot as plt



In [ ]:
# Connexion à ggdrive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Import du fichier via ggdrive
file_path = "/content/drive/MyDrive/Python M2/df_clean.csv" # Lien perso ggdrive
df = pd.read_csv(file_path, sep = ',')

## Arbre de décisions

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean.head()

Unnamed: 0  iid_pid    iid    id  partner    pid  int_corr  age_o  \
0           0   6804.0  453.0  14.0     10.0  439.0      48.0   29.0   
1           1   6803.0  453.0  14.0      9.0  438.0      31.0   23.0   
2           2   6802.0  453.0  14.0      8.0  437.0       4.0   23.0   
3           3   6801.0  453.0  14.0      7.0  436.0      59.0   23.0   
4           4   6800.0  453.0  14.0      6.0  435.0     -17.0   22.0   

   pf_o_att  pf_o_sin  ...  samerace  race_o  field_cd  race             from  \
0      20.0      10.0  ...         0     2.0       1.0   4.0  Shanghai, China   
1      14.0      15.0  ...         0     2.0       1.0   4.0  Shanghai, China   
2      15.0      15.0  ...         0     2.0       1.0   4.0  Shanghai, China   
3      28.0       8.0  ...         0     2.0       1.0   4.0  Shanghai, China   
4      25.0       5.0  ...         0     1.0       1.0   4.0  Shanghai, China   

   zipcode  goal  date  go_out  career_c  
0  210,009   2.0   6.0     5.0       1.0  
1  210,009   2.0   6.0     5.0       1.0  
2  210,009   2.0   6.0     5.0       1.0  
3  210,009   2.0   6.0     5.0       1.0  
4  210,009   2.0   6.0     5.0       1.0  

[5 rows x 63 columns]

In [ ]:
X = df_clean[df_clean.columns[3:]] # On enlève la colonne ID et la colonne CLASSE
X.pop('match')
y = df_clean.match # Colonne var à prédire

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6804 entries, 0 to 6803
Data columns (total 59 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        6804 non-null   float64
 1   partner   6804 non-null   float64
 2   pid       6804 non-null   float64
 3   int_corr  6804 non-null   float64
 4   age_o     6804 non-null   float64
 5   pf_o_att  6804 non-null   float64
 6   pf_o_sin  6804 non-null   float64
 7   pf_o_int  6804 non-null   float64
 8   pf_o_fun  6804 non-null   float64
 9   pf_o_amb  6804 non-null   float64
 10  pf_o_sha  6804 non-null   float64
 11  attr_o    6804 non-null   float64
 12  sinc_o    6804 non-null   float64
 13  intel_o   6804 non-null   float64
 14  fun_o     6804 non-null   float64
 15  amb_o     6804 non-null   float64
 16  shar_o    6804 non-null   float64
 17  age       6804 non-null   float64
 18  imprace   6804 non-null   float64
 19  imprelig  6804 non-null   float64
 20  income    6804 non-null   floa

In [ ]:
print(X.shape, y.shape)

(6804, 59) (6804,)


In [ ]:
y.value_counts()

0    5658
1    1146
Name: match, dtype: int64

In [ ]:
# Utilisation du model_selection de sklearn
import sklearn
from sklearn import model_selection
# Affichage de la version
print(sklearn.__version__)

1.0.2


In [ ]:
X_dummy = pd.get_dummies(X, drop_first=True)


In [ ]:
X_dummy.shape

(6804, 680)

In [ ]:
X_app, X_test, y_app, y_test = model_selection.train_test_split(X_dummy,y, train_size=0.7, random_state=0, stratify=y)


In [ ]:
print(X_app.shape, X_test.shape, y_app.shape, y_test.shape)

(4762, 680) (2042, 680) (4762,) (2042,)


In [ ]:
# Vérification de l'égalité de distribution entre y_app et y_test
y_app.value_counts(normalize=True)

0    0.831583
1    0.168417
Name: match, dtype: float64

In [ ]:
# Vérification de l'égalité de distribution entre y_app et y_test
y_test.value_counts(normalize=True)

0    0.831538
1    0.168462
Name: match, dtype: float64

In [ ]:
# Load libraries
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation


In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(random_state=0)

# Train Decision Tree Classifer
clf = clf.fit(X_app,y_app)

#Predict the response for test dataset
y_pred = clf.predict(X_test)


In [ ]:
# Model Accuracy, how often is the classifier correct?
print("F1 Score:",metrics.f1_score(y_test, y_pred, average = "macro"))
print(metrics.confusion_matrix(y_test,y_pred))


F1 Score: 0.574354491662184
[[1442  256]
 [ 240  104]]


In [ ]:
X_app, X_test, y_app, y_test = model_selection.train_test_split(X_dummy,y, train_size=0.7, random_state=0, stratify=y)
X_app

id  partner    pid  int_corr  age_o  pf_o_att  pf_o_sin  pf_o_int  \
5386   5.0     14.0   89.0       0.0   27.0      25.0      15.0      20.0   
2308   4.0      2.0  309.0      53.0   32.0      20.0      20.0      20.0   
1702   5.0      6.0  366.0      19.0   27.0      14.0      18.0      17.0   
861   11.0      9.0  405.0      -4.0   30.0      30.0      25.0      20.0   
702    1.0     16.0  394.0       1.0   24.0      18.0      19.0      16.0   
...    ...      ...    ...       ...    ...       ...       ...       ...   
3546  13.0     10.0  203.0       5.0   22.0      16.0      20.0      18.0   
6729   8.0      5.0   15.0     -23.0   24.0      30.0      10.0      20.0   
2941  14.0     20.0  292.0      -1.0   28.0      20.0      18.0      20.0   
197    6.0     13.0  452.0      12.0   29.0      35.0      30.0      25.0   
4212   9.0      4.0  177.0       7.0   22.0    1509.0    1698.0    1698.0   

      pf_o_fun  pf_o_amb  ...  career_c_17.0  career_c_2.0  career_c_3.0  \
5386      20.0      20.0  ...              0             1             0   
2308      20.0      10.0  ...              0             1             0   
1702      16.0      15.0  ...              0             0             0   
861       15.0       5.0  ...              0             0             0   
702       15.0      15.0  ...              0             0             0   
...        ...       ...  ...            ...           ...           ...   
3546      20.0      18.0  ...              0             0             0   
6729      10.0      10.0  ...              0             0             0   
2941      17.0      10.0  ...              0             1             0   
197        5.0       0.0  ...              0             0             0   
4212    1698.0    1887.0  ...              0             0             0   

      career_c_4.0  career_c_5.0  career_c_6.0  career_c_7.0  career_c_8.0  \
5386             0             0             0             0             0   
2308             0             0             0             0             0   
1702             1             0             0             0             0   
861              0             0             0             0             0   
702              0             0             0             0             0   
...            ...           ...           ...           ...           ...   
3546             0             0             1             0             0   
6729             0             0             1             0             0   
2941             0             0             0             0             0   
197              0             0             0             0             0   
4212             0             0             0             1             0   

      career_c_9.0  career_c_Missing value  
5386             0                       0  
2308             0                       0  
1702             0                       0  
861              0                       0  
702              0                       0  
...            ...                     ...  
3546             0                       0  
6729             0                       0  
2941             0                       0  
197              0                       0  
4212             0                       0  

[4762 rows x 680 columns]

In [ ]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE

In [ ]:
sm = SMOTE(random_state=42, sampling_strategy=0.5, k_neighbors=5)
X_res, y_res = sm.fit_resample(X_app, y_app)

In [ ]:
# Create Decision Tree classifer object
clf2 = DecisionTreeClassifier(random_state=0,min_samples_split=15,min_samples_leaf=20)

# Train Decision Tree Classifer
clf2 = clf2.fit(X_res, y_res)

#Predict the response for test dataset
y_pred2 = clf2.predict(X_test)


In [ ]:
# Model Accuracy, how often is the classifier correct?
print("F1 Score:",metrics.f1_score(y_test, y_pred2, average = "macro"))
print(metrics.confusion_matrix(y_test,y_pred2))

F1 Score: 0.5923707897793263
[[1502  196]
 [ 244  100]]


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
clf3 = GradientBoostingClassifier(n_estimators=175, learning_rate=1,max_depth=1, random_state=0,min_samples_split=15, min_samples_leaf=20).fit(X_res, y_res)
y_pred3 = clf3.predict(X_test)
print("F1 Score :",metrics.f1_score(y_test, y_pred3, average = "macro"))
print(metrics.confusion_matrix(y_test,y_pred3))

F1 Score : 0.611454277427935
[[1568  130]
 [ 250   94]]
