In [32]:
# Chargement package
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

In [33]:
# Connexion à ggdrive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [34]:
# Import du fichier via ggdrive
file_path_train_clean = "/content/drive/MyDrive/Python M2/train_clean.csv" # Lien perso ggdrive
file_path_sub_clean = "/content/drive/MyDrive/Python M2/sub_clean.csv"
df = pd.read_csv(file_path_train_clean, sep = ',',index_col = [0])
df_submission=pd.read_csv(file_path_sub_clean, sep = ',',index_col = [0])

## Arbre de décisions

In [35]:
df_clean = df.copy()

In [36]:
df_clean.head()

iid_pid  gender  condtn  samerace  race_o  field_cd  race  goal  date  \
0     6804       1       2         0     2.0       1.0   4.0   2.0   6.0   
1     6803       1       2         0     2.0       1.0   4.0   2.0   6.0   
2     6802       1       2         0     2.0       1.0   4.0   2.0   6.0   
3     6801       1       2         0     2.0       1.0   4.0   2.0   6.0   
4     6800       1       2         0     1.0       1.0   4.0   2.0   6.0   

   go_out  ...  shopping  yoga  exphappy  attr1_1  sinc1_1  intel1_1  fun1_1  \
0     5.0  ...       4.0   1.0       6.0     30.0     30.0      30.0     5.0   
1     5.0  ...       4.0   1.0       6.0     30.0     30.0      30.0     5.0   
2     5.0  ...       4.0   1.0       6.0     30.0     30.0      30.0     5.0   
3     5.0  ...       4.0   1.0       6.0     30.0     30.0      30.0     5.0   
4     5.0  ...       4.0   1.0       6.0     30.0     30.0      30.0     5.0   

   amb1_1  shar1_1  match  
0     0.0      5.0      0  
1     0.0      5.0      0  
2     0.0      5.0      0  
3     0.0      5.0      0  
4     0.0      5.0      0  

[5 rows x 54 columns]

In [37]:
X = df_clean[df_clean.columns[1:]] # On enlève la colonne ID et la colonne CLASSE
X.pop('match')
y = df_clean.match # Colonne var à prédire

In [38]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6804 entries, 0 to 6803
Data columns (total 52 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   gender    6804 non-null   int64  
 1   condtn    6804 non-null   int64  
 2   samerace  6804 non-null   int64  
 3   race_o    6804 non-null   float64
 4   field_cd  6804 non-null   float64
 5   race      6804 non-null   float64
 6   goal      6804 non-null   float64
 7   date      6804 non-null   float64
 8   go_out    6804 non-null   float64
 9   career_c  6804 non-null   float64
 10  int_corr  6804 non-null   float64
 11  age_o     6804 non-null   float64
 12  pf_o_att  6804 non-null   float64
 13  pf_o_sin  6804 non-null   float64
 14  pf_o_int  6804 non-null   float64
 15  pf_o_fun  6804 non-null   float64
 16  pf_o_amb  6804 non-null   float64
 17  pf_o_sha  6804 non-null   float64
 18  attr_o    6804 non-null   float64
 19  sinc_o    6804 non-null   float64
 20  intel_o   6804 non-null   floa

In [39]:
print(X.shape, y.shape)

(6804, 52) (6804,)


In [40]:
y.value_counts()

0    5658
1    1146
Name: match, dtype: int64

In [41]:
# Utilisation du model_selection de sklearn
import sklearn
from sklearn import model_selection
# Affichage de la version
print(sklearn.__version__)

1.0.2


In [42]:
X_app, X_test, y_app, y_test = model_selection.train_test_split(X,y, train_size=0.7, random_state=0, stratify=y)


In [43]:
print(X_app.shape, X_test.shape, y_app.shape, y_test.shape)

(4762, 52) (2042, 52) (4762,) (2042,)


In [44]:
# Vérification de l'égalité de distribution entre y_app et y_test
y_app.value_counts(normalize=True)

0    0.831583
1    0.168417
Name: match, dtype: float64

In [45]:
# Vérification de l'égalité de distribution entre y_app et y_test
y_test.value_counts(normalize=True)

0    0.831538
1    0.168462
Name: match, dtype: float64

In [46]:
# Load libraries
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation


In [47]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(random_state=0)

# Train Decision Tree Classifer
clf = clf.fit(X_app,y_app)

#Predict the response for test dataset
y_pred = clf.predict(X_test)


In [48]:
# Model Accuracy, how often is the classifier correct?
print("F1 Score:",metrics.f1_score(y_test, y_pred, average = "macro"))
print(metrics.confusion_matrix(y_test,y_pred))


F1 Score: 0.5731989200398312
[[1425  273]
 [ 236  108]]


In [49]:
X_app, X_test, y_app, y_test = model_selection.train_test_split(X,y, train_size=0.7, random_state=0, stratify=y)

In [50]:
X_app.shape

(4762, 52)

In [51]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE

In [52]:
sm = SMOTE(random_state=42, sampling_strategy=0.5, k_neighbors=5)
X_res, y_res = sm.fit_resample(X_app, y_app)

In [53]:
X_res.shape

(5940, 52)

In [54]:
# Create Decision Tree classifer object
clf2 = DecisionTreeClassifier(random_state=0,min_samples_split=15,min_samples_leaf=20)

# Train Decision Tree Classifer
clf2 = clf2.fit(X_res, y_res)

#Predict the response for test dataset
y_pred2 = clf2.predict(X_test)


In [55]:
# Model Accuracy, how often is the classifier correct?
print("F1 Score:",metrics.f1_score(y_test, y_pred2, average = "macro"))
print(metrics.confusion_matrix(y_test,y_pred2))

F1 Score: 0.5827551681926512
[[1511  187]
 [ 253   91]]


In [56]:
from sklearn.ensemble import GradientBoostingClassifier

In [57]:
clf3 = GradientBoostingClassifier(n_estimators=175, learning_rate=1,max_depth=1, random_state=0,min_samples_split=15, min_samples_leaf=20).fit(X_res, y_res)
y_pred3 = clf3.predict(X_test)
print("F1 Score :",metrics.f1_score(y_test, y_pred3, average = "macro"))
print(metrics.confusion_matrix(y_test,y_pred3))

F1 Score : 0.6321383534498289
[[1595  103]
 [ 245   99]]


In [59]:
y_pred_sub=clf3.predict(df_submission.iloc[:,1:])

In [63]:
len(y_pred_sub)

1574

In [62]:
df_submission.shape

(1574, 53)

In [ ]:
list_var_sub=df_submission.columns.tolist()

In [ ]:
list_var_test=X_test.columns.tolist()

In [ ]:
list_diff=[]
for element in list_var_sub :
  if element not in list_var_test:
    list_diff.append(element)

print(list_diff)